/*
389. Find the Difference
Easy

You are given two strings s and t.

String t is generated by random shuffling string s and then add one more letter at a random position.

Return the letter that was added to t.
*/
class Solution {
public:
    char findTheDifference(string s, string t) {
        map<char,int> m;
        char ans;
        for(int i=0;i<t.size();i++){
            m[t[i]]++;
        }
        for(int i=0;i<s.size();i++){
            m[s[i]]--;
        }
        for(auto i: m){
            if(i.second>0)
                ans = i.first;
        }
        return ans;
    }
};